backend:
  name: github
  repo: Davidouu/sq-docs
  branch: master

media_folder: "docs/assets"
public_folder: "/assets"

collections:
  - name: "modules"
    label: "Modules"
    folder: "docs/modules"
    create: false
    format: "frontmatter"
    nested:
      depth: 3
      index_file: false
      summary: "{{title}}"
    fields:
      - { name: title, label: "Titre", widget: string }
      - { name: body,  label: "Contenu", widget: markdown }
